### ISSUE TITLE
ModuleNotFoundError: No module named 'hcmgis_library' 

### ISSUE THREAD

**Issue by pigreco** [thangqd/HCMGIS#9]
Impossibile caricare il plugin 'HCMGIS' a causa di un errore chiamando il metodo classFactory() 

ModuleNotFoundError: No module named 'hcmgis_library' 
Traceback (most recent call last):
  File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\hcmgis_dialogs.py", line 32, in 
    from .hcmgis_library import *
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\hcmgis_library.py", line 14, in 
    import xlrd
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'xlrd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\__init__.py", line 11, in classFactory
    from .hcmgis_menu import hcmgis_menu
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\hcmgis_menu.py", line 11, in 
    from .hcmgis_dialogs import *
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\hcmgis_dialogs.py", line 34, in 
    from hcmgis_library import *
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'hcmgis_library'

```

Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versione di QGIS: 3.12.2-București București, 8a1fb33634 

Percorso Python:
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos
C:/OSGEO4~1/apps/qgis/./python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\pigre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
.
D:/GitHub/COVID-19_ITA
```

## OSGeo4W64 win 10

**Comment by thangqd** [comment]
Thanks for your comments.
Try this in your Mac to install xlrd for python: `pip install xlrd` and please tell me for any further problems

**Comment by pigreco** [comment]
thanks, it works!
